site_name: MkLorum
site_url: https://example.com/
nav:
  - Home: index.md
  - About: about.md
  - Code Reference:
    - Parser Types: workbook_compiler-reference.md
theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]